# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.6'
- script: pip install -r requirements.txt
  displayName: 'Install App requirements'
- task: SnykSecurityScan@1
  inputs:
    serviceConnectionEndpoint: 'snyk-free'
    testType: 'app'
    monitorWhen: 'never'
    failOnIssues: true
- task: APIContractSecurityAudit@3
  inputs:
    apiToken: '$(42C_API_TOKEN)'
    defaultCollectionName: 'VAMPI'
    logLevel: DEBUG
